### ISSUE TITLE
StripPanosPackaging panics sometimes

### ISSUE THREAD

**Issue by freakytoad1** [PaloAltoNetworks/pango#109]
## Describe the bug

Sometimes when doing calls to panorama the function within PanGo, util.StripPanosPackaging, will panic causing my whole go application using this code to crash.

## Expected behavior

To not have any unhandled panics and to have an error returned if panorama or a firewall is unable to accept the request. I am just speculating that panorama denying the request is the issue as the panics happen every few days and not at expected times.

## Current behavior

On occasions, the function util.StripPanosPackaging on line 203 causes a panic. See trace log below.

## Possible solution

In util.StripPanosPackaging, check the input []byte for lengths before doing slice operations on it. Line 203 in particular is causing a panic during some call operations.

## Steps to reproduce

This is very difficult to reproduce. I suspect it is because of concurrent calls to panorama eventually just getting dropped by panorama and there would be no response. I do limit calls to about 5 at a time but that can be difficult to enforce. In the panic trace I posted below it was during a get operation to get url categories but I have seen it happen to any call.

## Screenshots

```
panic: runtime error: slice bounds out of range [:-1]
goroutine 627672 [running]:
github.com/PaloAltoNetworks/pango/util.StripPanosPackaging({0xc004124c00, 0x0, 0x200}, {0x101ca01, 0x13})
/go/pkg/mod/github.com/!palo!alto!networks/pango@v0.10.2/util/util.go:203 +0x39f
github.com/PaloAltoNetworks/pango/namespace.(*Common).retrieve(0xc00053a7c0, {0x10055fa, 0x3}, {0xc0114f8480, 0xf2dc20?, 0x8}, 0x48?, {0x0?, 0x0?}, 0x1, ...)
/go/pkg/mod/github.com/!palo!alto!networks/pango@v0.10.2/namespace/common.go:130 +0xa2d
github.com/PaloAltoNetworks/pango/namespace.(*Common).Objects(0xc0010da1b8?, {0x10055fa, 0x3}, 0xc005b07cd0?, {0xec7460, 0xc00eab6288})
/go/pkg/mod/github.com/!palo!alto!networks/pango@v0.10.2/namespace/common.go:45 +0xa5
github.com/PaloAltoNetworks/pango/objs/custom/url.(*Panorama).GetAll(0xc0010da1b8, {0xc014bbe9c4, 0xa})
/go/pkg/mod/github.com/!palo!alto!networks/pango@v0.10.2/objs/custom/url/pano.go:70 +0x87
```

## Context

Doing multiple concurrent calls to panorama is a must. We have an extremely large environment with dozens of admins.

## Your Environment

- Version used: PanGo 0.10.2

I will post more information if I am able to more precisely track down when this occurs.

**Comment by freakytoad1** [comment]
Turned on pango.LogReceive to gather some more information and see the responses back from panorama. Seeing some code 7 responses and 22. The last response before the panic happens shows that the response was totally empty from panorama.

```
2023/09/07 13:07:57 Response = <response status="success" code="7"><result/></response>
2023/09/07 13:07:57 Response = <response status="unauth" code="22"><msg><line>Session timed out</line></msg></response>
2023/09/07 13:07:57 Response =
panic: runtime error: slice bounds out of range [:-1]

goroutine 1099 [running]:
github.com/PaloAltoNetworks/pango/util.StripPanosPackaging({0xc001780600, 0x0, 0x200}, {0x15ef5ce, 0x5})
	/home/test.lab/msavino/go/pkg/mod/github.com/!palo!alto!networks/pango@v0.10.2/util/util.go:203 +0x606
github.com/PaloAltoNetworks/pango/namespace.(*Common).retrieve(0xc00057fec0, {0x15e9641, 0x3}, {0xc00293a5a0, 0x8, 0x9}, 0x0, {0x0, 0x0}, 0x1, ...)
	/home/test.lab/msavino/go/pkg/mod/github.com/!palo!alto!networks/pango@v0.10.2/namespace/common.go:130 +0x13a7
github.com/PaloAltoNetworks/pango/namespace.(*Common).Objects(0xc00057fec0, {0x15e9641, 0x3}, 0xc00114b140, {0x14a7900, 0xc001d18a68})
	/home/test.lab/msavino/go/pkg/mod/github.com/!palo!alto!networks/pango@v0.10.2/namespace/common.go:45 +0x1ca
github.com/PaloAltoNetworks/pango/poli/nat.(*Panorama).GetAll(0xc000014a80, {0xc00106c090, 0xd}, {0x15faffd, 0xd})
	/home/test.lab/msavino/go/pkg/mod/github.com/!palo!alto!networks/pango@v0.10.2/poli/nat/pano.go:51 +0x11f
```

**Comment by shinmog** [comment]
this should be fixed in develop now, will be present in the next pango release
