### ISSUE TITLE
AllFromPanosConfig() only returns 1 result for policies

### ISSUE THREAD

**Issue by freakytoad1** [PaloAltoNetworks/pango#110]
## Describe the bug

2 Issues
1. AllFromPanosConfig() only returns a single result for nat and security policies.
2. The policy returned from AllFromPanosConfig() has duplicated items in slice fields.

## Expected behavior

1. Should return all policies requested.
2. Fields should only have the explicit data, not duplicated.

## Current behavior

1. A devicegroup has multiple [pre / post] [security / nat] policies. 

![image](https://github.com/PaloAltoNetworks/pango/assets/24303696/df7e29e2-b1c5-4566-93f6-ec8324fb8b4a)

2. Using AllFromPanosConfig("dgname", "pre-rulebase") only returns the first rule

Showing single returned item
![image](https://github.com/PaloAltoNetworks/pango/assets/24303696/b6282373-263a-4c79-84eb-c1ccf09b7f9e)

Showing that item as 'rule 1'
![image](https://github.com/PaloAltoNetworks/pango/assets/24303696/d93c2bb3-7c65-490b-bdc8-db33d17e9a95)

3. The fields that are slices have duplicated entries

![image](https://github.com/PaloAltoNetworks/pango/assets/24303696/e8a07597-de4a-4b19-a25c-96f564ccb190)

## Steps to reproduce

1. Setup panorama connection
2. LoadPanOSconfig with connection.RetrievePanosConfig("running")
3. Call connection.Policies.Security.AllFromPanosConfig("dgname", "pre-rulebase")
4. Inspect the returned policy information

## Context

Want to start using the 'FromPanosConfig' functions instead of reaching to panorama for each API call. Will help us reduce load on panorama and speed up querying of information.

## Your Environment
- Version used: v0.10.2

**Comment by freakytoad1** [comment]
@shinmog  That is awesome! Thanks for the work. Any indication of when that release is coming?

**Comment by shinmog** [comment]
If you want to use pango from `develop` it's there now.  Otherwise I'm not exactly sure when this will go live.

**Comment by shinmog** [comment]
To give any kind of guidance, I suspect that the new pango will go live somewhere in the neighborhood of Q3 2024.
