### ISSUE TITLE
Missing interface link data

### ISSUE THREAD

**Issue by bl4ko** [PaloAltoNetworks/pango#115]
## Describe the bug

When calling `c.Network.EthernetInterface.Get()` link data of interface is missing, but on web ui it is visible.

## Expected behavior

The response should contain link data like this:

```
{
  Name:ethernet1/1 
  Mode:layer3 
  ...
  LinkSpeed: 1000
  LinkDuplex: Full
  LinkState: auto 
  ...
}
```

## Current behavior

```
{
  Name:ethernet1/1 
  Mode:layer3 
  ...
  LinkSpeed: 
  LinkDuplex: 
  LinkState:auto 
  ...
}
```

## Steps to reproduce

```go
ethInterface, _ := c.Network.EthernetInterface.Get("ethernet1/1")
fmt.Printf("%+v\n", ethInterface)
```

## Screenshots

<img width="1140" alt="paloalto_debug" src="https://github.com/PaloAltoNetworks/pango/assets/83308880/5856dc33-dc04-40a9-8b71-1cfa0388962a">

## Context

Trying to collect all of the interface data from paloalto api.

## Your Environment

- Paloalto version:  10.1.11
- Pango version: v0.10.2
- Operating System and version (desktop or mobile): Ubuntu 22.04.2 x86_64

**Comment by mr-steveb** [comment]
hi there,

I was looking at this today and wondering, is this actually a bug? from what I understand, 'Get' action for configuration will get the candidate configuration, not the running configuration (the 'Show' action does this I believe, see https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-panorama-api/pan-os-xml-api-request-types/pan-os-xml-api-request-types-and-actions/configuration-actions/actions-for-reading-a-configuration#id4c4be55e-8eaf-4b69-8c82-dda09237d0b1 ). 

If I set the speed, duplex and state manually without committing, and run the test mentioned above, I get the expected output:

_{Name:ethernet1/1 Mode:layer3 StaticIps:[] EnableDhcp:false CreateDhcpDefaultRoute:false DhcpDefaultRouteMetric:0 Ipv6Enabled:false Ipv6InterfaceId: ManagementProfile: Mtu:0 AdjustTcpMss:false NetflowProfile: LldpEnabled:false LldpProfile: LldpHaPassivePreNegotiation:false LacpHaPassivePreNegotiation:false **LinkSpeed:100 LinkDuplex:half LinkState:up**_

apologies if I've missed the mark

**Comment by bl4ko** [comment]
Hello, thanks for the response. 
I'm not pretty familiar with pan-os api and I don't know if this is a bug or not. I'm trying to fetch the link state data for ethernet interfaces and both `Show` and `Get` actions return me empty values, even though the values are visible on webui (above)

Here providing example also for `Show` action:

```go
ethInterface, _ := c.Network.EthernetInterface.Show("ethernet1/1")
fmt.Printf("%+v\n", ethInterface)
```

return values:

```
{
  Name:ethernet1/1 
  Mode:layer3 
  ...
  LinkSpeed: 
  LinkDuplex: 
  LinkState:auto 
  ...
  DhcpSendHostnameValue: raw:map[ndp:
      <enabled>no</enabled>
{
```

I guess the problem is when **link settings** are set to **auto** the api won't return any data?

**Comment by mr-steveb** [comment]
Yeah this could be a bug on the Palo Alto side in the sense that if the LinkSpeed, Duplex or State is not explicitly or are left on the default 'auto' as you said, then it just returns a blank value, I haven't tested this though. One would have to set speed, duplex and state, commit the change, then run test code calling Show to see if returns a non-blank value.

It doesn't seem to be documented, but I was looking through the available methods for a Client and noticed the Op() method:

func (c *pango.Client) Op(req interface{}, vsys string, extras interface{}, ans interface{}) ([]byte, error)

Op runs an operational or "op" type command.

The req param can be either a properly formatted XML string or a struct that can be marshalled into XML.

The vsys param is the vsys the op command should be executed in, if any.

The extras param should be either nil or a url.Values{} to be mixed in with the constructed request.

The ans param should be a pointer to a struct to unmarshal the response into or nil.

Any response received from the server is returned, along with any errors encountered.

This seems to allow you to run operational commands similarly to what is outlined here: https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-panorama-api/pan-os-xml-api-request-types/run-operational-mode-commands-api

I tested this myself and it seems to pull the operational data, assuming you pass the correct command in xml format:

```
	xmlString := "<show><interface>ethernet1/12</interface></show>"
	vsys := "vsys1"

	// Process the response data

	ethInterface, _ := c.Op(xmlString, vsys, nil, nil)
	fmt.Printf("%+v\n", string(ethInterface))
```

output:

```
<response status="success"><result>
  <dp>dp0</dp>
  <hw>
    <name>ethernet1/12</name>
    <id>75</id>
    <speed_c>auto</speed_c>
    <duplex_c>auto</duplex_c>
    <state_c>auto</state_c>
    <speed>1000</speed>
    <duplex>full</duplex>
    <state>up</state>
    ...
```

hopefully that helps

**Comment by bl4ko** [comment]
Thanks this method works fine
