### ISSUE TITLE
Feature Request - Application Groups

### ISSUE THREAD

**Issue by freimer** [PaloAltoNetworks/pango#12]
Would it be possible to add Application Group support, for both firewall and Panorama?  I can try, but I'm not a Go expert...

**Comment by shinmog** [comment]
Shouldn't be too bad since the pandevice work is already done, will look into it.

**Comment by shinmog** [comment]
@freimer 

Looking at pandevice, there's applications, application groups, app filters, and app containers.  Is it all of the above you are looking for?

**Comment by freimer** [comment]
For now just application groups...
