### ISSUE TITLE
LLDP not fully supported in Ethernet interfaces type Layer3

### ISSUE THREAD

**Issue by chadell** [PaloAltoNetworks/pango#36]
## Describe the bug

While working on changing LLDP enable status in ethernet and aggregated interfaces, I noticed that in ethernet interfaces, specially layer3 ones, the status of LLDP enable can't be changed from `false` to `true` via API.

Checking the code to compare ethernet vs aggregated interfaces, because the second ones are working fine, I noticed that LLDP is specified in layer3 aggregated interfaces ([here](https://github.com/PaloAltoNetworks/pango/blob/8c48226c9bd07bfb78470b52d94e19e034425c54/netw/interface/aggregate/entry.go#L238) for instance) but I don't see the same logic happening [here](https://github.com/PaloAltoNetworks/pango/blob/8c48226c9bd07bfb78470b52d94e19e034425c54/netw/interface/eth/entry.go#L815) 

## Expected behavior

Ethernet and aggregated layer3 interfaces should accept enabling LLDP.

## Current behavior

ethernet layer3 should be able to take LLDP enabled `true`

## Possible solution

Match the behaviour that is also seen at layer2 ethernet interfaces.

## Steps to reproduce

There are two ways to check, one way is just getting data via `Client.Network.EthernetInterface.Show(name)` and you will see that LLDP enabled is always `false` even being enabled, and if you modify the entry to `true` and pushed the change is not taken into account.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): 
- Operating System and version (desktop or mobile): 
- Link to your project:

**Comment by shinmog** [comment]
Whupps, should be fixed now.

**Comment by chadell** [comment]
> Whupps, should be fixed now.

yes, it is.
Thanks!
