### ISSUE TITLE
Return policy rule usage data

### ISSUE THREAD

**Issue by arusso** [PaloAltoNetworks/pango#40]
### Is your feature request related to a problem?

I'd like to be able to read policy rule usage data  (hit count / first hit / last hit) for NAT/Security policy statements policy rules, in my case to report on policy statements that may no longer be used.

### Describe the solution you'd like

I'd like to see `HitCount int`, `LastHit time.Time`, `FirstHit time.Time` fields added to the respective `*.Entry`structs.

### Describe alternatives you've considered

None

### Additional context

We have tooling around generating NAT and Security policy rules from a database and we'd like to export the last hit date back into that database so we can use existing tooling to troubleshoot and identify rules that are no longer used.

**Comment by shinmog** [comment]
Hit count added in PAN-OS 9.0

The rule hit count stuff seems to be op commands, so this data should not be attached to the Entry normalization objects.

Alternatively, this can be added as a function in the respective policy namespaces.

**Comment by arusso** [comment]
Ya I noticed that as I started looking at how this might be done in hopes it was a simple field addition to the struct. I'm not really invested in any method and a policy-level function seems the pretty intuitive to me now that I've peeked at the internals a little.

**Comment by shinmog** [comment]
This is added now.  You can use the namespace functions off of the firewall struct:

```go
rules, err := fw.Policies.Security.HitCount("vsys1", nil)
```

or you can invoke it yourself for rulebases that are not yet natively supported by pango (the structs are in the `util` package, just mimic what the above function is doing).

**Comment by arusso** [comment]
Works great, except I had to hack around the version limit you put in place -- rule usage tracking was introduced in 8.1 but it's set to block anything below 9.0.

**Comment by shinmog** [comment]
I don't always catch comments on closed issues, so please open a new issue (or reopen this one if it's the same error) in the future.

In any case, I've lowered the min version to 8.1 for the policy namespaces.

**Comment by arusso** [comment]
Will do, thanks again.
