### ISSUE TITLE
Support for certificate profiles

### ISSUE THREAD

**Issue by mrboogiee** [PaloAltoNetworks/pango#42]
### Is your feature request related to a problem?

Currently the creation and maintenance of certificate profiles is not yet possible using pango. As certificate profiles are used in (a.o.) the creation of the EDL objects, it would be very useful if the certificate profiles can also be managed through pango.

### Describe the solution you'd like

certificate profile management support in the same manner as fe. security profile management

### Describe alternatives you've considered

This can of course be achieved through direct XML calls, but it is a better solution to have this embedded in the standard pango library

### Additional context

I am trying to automate the management of PAN devices into a fully (PANOS version independent) automated fashion in which I would love to not require the creation of any direct XML calls as that would still create a potential version dependency problem which should not be the case when using pango.

**Comment by shinmog** [comment]
Just added support for this.
