### ISSUE TITLE
Virtual Router entry has all metrics to 0

### ISSUE THREAD

**Issue by chadell** [PaloAltoNetworks/pango#44]
## Describe the bug

When instantiating a `router.Entry` all the protocols default distance metrics are 0.

## Expected behavior

Report the values seen in the GUI

## Current behavior

All distance metric are 0.

Even though, I see an exported method `Defaults()` to initialise it https://github.com/PaloAltoNetworks/pango/blob/master/netw/routing/router/entry.go#L49
but I would assume that the library should call it and not delegate it to the user

## Steps to reproduce

1. Instantiate a `router.Entry`
2. Check data

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by shinmog** [comment]
Let's say that you want the default values for a virtual router, except for 3 admin distances.  What would you want the code to look like?

One way I can think of is to have a `Defaults()` that returns an object that has default params set:

```go
o := router.Defaults()
o.Name = "my router"
o.StaticDist = 12
o.OspfIntDist = 42
o.RipDist = 100
```

The other way is with a `Defaults()`, like what currently exists:

```go
o := router.Entry{
  Name: "my router",
  StaticDist: 12,
  OspfIntDist: 42,
  RipDist: 100,
}
o.Defaults()
```

Either seem to get the job done, and which you like feels to be a personal preference..?

**Comment by shinmog** [comment]
Actually, let me give a little more context here:

I originally intended to have a way to get Default values for each normalization in pango, but I've actually stopped having a `Defaults()` in most of the new normalizations because of the above.  Having to undo what `Defaults()` does, or hope that `Defaults()` doesn't undo something you've specified, seems weird.

It also gets a bit more complicated if a new version of PAN-OS adds a param that has a non-empty default value.

**Comment by chadell** [comment]
thanks @shinmog  for the feedback. Actually, I realised that I explained it wrong... will try to do a better job now:

I'm actually not initalizing the Entry but getting it via `Show` command:
`vrEntry, err := pango.Firewall.Client.Network.VirtualRouter.Show(vrName)`

where the `vrEntry` had this value:
![image](https://user-images.githubusercontent.com/15998111/102918249-dd0f3580-4486-11eb-8919-1188281d52fe.png)

curiously, the only value that is defined is `OspfExtDist: 110` that comes from a previous `Edit` I did: `err = pango.Firewall.Client.Network.VirtualRouter.Edit(vrName, *entry)`

Maybe I'm wrong, but it looks that if the default metric has not been explicitly defined in the VR config, the default metrics that you get are all 0, when I would expect to receive the default values.

**Comment by chadell** [comment]
closing this as I realized that the API doesn't return the data and from the `config` section
