### ISSUE TITLE
Commit By not working

### ISSUE THREAD

**Issue by reneherrero** [PaloAltoNetworks/pango#46]
## Not able to commit changes by a specific user

Setting the list of admins seems to have no effect
```
	panCommit := commit.PanoramaCommit{
		Description: message,
		Admins:      []string{"some_user"},
	}
	req, _, err := c.pan.Commit(panCommit, "", nil)
```

## Expected behavior

Expecting changes done simultaneously via the UI by a diferent user to remain unaffected

Tried:
1- passing `panCommit.Element()` to the `pan.Commit` function (no effect)
2- passing different action to `pan.Commit` (no effect) -> documentation doesn't list the possible values

Not sure if it's a bug, or if the problem is between the keyboard and the chair...

**Comment by shinmog** [comment]
I cannot reproduce what you're describing.  Here's what I did:

1. Login to the GUI as the "admin" user and verified that there are no outstanding changes.
2. Create a new user, "pango" as a superuser
3. Commit (to the Panorama)
4. Navigate to Objects > Address and create a new address object
5. Click Commit > Commit to Panorama, then select "Commit changes made by" to verify that the "admin" user shows up, then click Cancel to keep the change pending
6. Ran a pango script (see below) to perform a change and then do a partial commit
7. Refresh the GUI and click Commit > Commit to Panorama, then select "Commit changes made by" again and verify that "pango" shows as a selectable user
8. Click Cancel to keep all changes as pending
9. Modify the script by commenting out the "return" statement, which will allow the script to commit
10. Run the script
11. Refresh the GUI, then click Commit > Commit to Panorama again, selecting "Commit changes made by"

The result of step 11 above is that the "pango" user is not there anymore, but the "admin" user is still there.

Here is the script I used (you'll need to substitute in a real IP address to the Panorama client):

```go
package main

import (
    "log"
    _ "fmt"

    "github.com/PaloAltoNetworks/pango"
    "github.com/PaloAltoNetworks/pango/commit"
    "github.com/PaloAltoNetworks/pango/objs/addr"
)

func main() {
    var err error

    c := &pango.Panorama{Client: pango.Client{
        Hostname: "127.0.0.1",
        Username: "pango",
        Password: "pango",
    }}

    if err = c.Initialize(); err != nil {
        log.Fatalf("Failed init: %s", err)
    }

    ip1, ip2 := "192.168.1.1", "127.0.0.1"
    o := addr.Entry{
        Name: "pango made",
        Type: addr.IpNetmask,
        Value: "192.168.1.1",
    }

    lo, err := c.Objects.Address.Get("shared", o.Name)
    if err == nil {
        switch lo.Value {
        case ip1:
            log.Printf("Switching ip to %q", ip2)
            o.Value = ip2
        default:
            log.Printf("Restoring ip to %q", ip1)
            o.Value = ip1
        }
    } else {
        log.Printf("Not present, so ip will be %q", o.Value)
    }

    if err = c.Objects.Address.Edit("shared", o); err != nil {
        log.Fatalf("Failed: %s", err)
    }

    // Comment this out after verifying that the "pango" user shows as having
    // pending changes.
    return

    cmt := commit.PanoramaCommit{
        Description: "pango admin partial commit check",
        Admins: []string{"pango"},
    }
    c.Logging |= pango.LogSend
    job, b, err := c.Commit(cmt, "", nil)
    if err != nil {
        log.Printf("Err: %s", err)
    }
    log.Printf("Resp (%d): %s", job, b)

    c.Logging = pango.LogAction | pango.LogOp

    if err = c.WaitForJob(job, 1, nil); err != nil {
        log.Printf("Failed commit: %s", err)
    }
}
```

**Comment by reneherrero** [comment]
Appreciate you taking the time to look into this Garfield.

Ok, here's the scoop.  I tried your code/steps and it gave the expected behavior which left me stomped.  So I started looking for differences and ran all kinds of permutations to try to narrow down the search radius.

Didn't find a solution, but I did find a few interesting things:
1- Creating and updating operations commit all pending changes by all users.  Deleting on the other hand doesn't have that effect: leaves changes done by another user uncommitted.
2- I created two objects with admin, a shared and another on a device group.  When I do a Create or Update, the shared object stays uncommitted, but the object belonging to the same device group as the objects I created gets committed.
3- Also noticed your code uses an `Edit` to create objects.  I'm using `Set` and `VerifiableSet`.  Not sure if that can have something to do with it.
4- Also tried creating both shared and device group objects with two different admins via the UI.  Doing a commit by via the UI yields the expected result which leads me to think it's something with the library.

Does this ring a bell?  I also tried setting the device group in the commit, but I don't see any difference in behavior?

**Comment by shinmog** [comment]
With your third bullet point, no, playing with security rules and using `Set()` / `VerifiableSet()` doesn't change anything, just where the pending change is located.

With your second bullet point, I started wondering if the problem is a commit that both a) mentions one or more admins and b) targets a specific device group is the issue, but that did not turn out to be an issue.  Here's the steps I took:

1. Using any admin account, create two users, "pango" and "pango2", and a device group, "pangoTesting"
2. Commit > Commit to Panorama
3. Still as this admin, add "adminObj" to the "pangoTesting" device group, then logout
4. Login as "pango"
5. Create an address object in the "pangoTesting" device group, "pangoObj", then logout
6. Login as "pango2"
7. Create an address object in the "pangoTesting" device group, "pango2Obj"
8. Click Commit > Commit to Panorama > Commit Changes made by and open the window to verify that "admin", "pango", and "pango2" all show up as having pending changes
9. Run the commit script below, which should commit only the changes made by the "pango" user
10. Refresh the GUI and click Commit > Commit to Panorama > Commit Changes Made By and expand the window

When I do this, I see "admin" and "pango2" still have pending changes, which is as expected.

With regards to your fourth bullet point, I am also enabling `pango.LogSend` for the commits in these scripts so that I can compare what pango is doing to what the GUI is doing (using "https://<ip>/debug"), I do not see a difference there.

At this point...  I don't know what else to try.  I am going to need specific repro steps, because everything I'm trying seems like there is no issue with pango.

Here is the script.  As before, substitute a real IP address for your Panorama:

```go
package main

import (
    "log"

    "github.com/PaloAltoNetworks/pango"
    "github.com/PaloAltoNetworks/pango/commit"
)

func main() {
    var err error

    c := &pango.Panorama{Client: pango.Client{
        Hostname: "127.0.0.1",
        Username: "pango",
        Password: "pango",
    }}

    if err = c.Initialize(); err != nil {
        log.Fatalf("Failed init: %s", err)
    }

    cmt := commit.PanoramaCommit{
        Description: "Should just do pango changes",
        Admins: []string{"pango"},
        DeviceGroups: []string{"pangoTesting"},
    }
    c.Logging |= pango.LogOp | pango.LogSend
    j2, b2, err := c.Commit(cmt, "", nil)
    if err != nil {
        log.Printf("Err in commit: %s")
    }
    log.Printf("Resp jobid:%d - %q", j2, b2)
    c.Logging = pango.LogAction | pango.LogOp
    if err = c.WaitForJob(j2, 1, nil); err != nil {
        log.Printf("Failed commit: %s", err)
    } else {
        log.Printf("Commit ok")
    }
}
```

**Comment by reneherrero** [comment]
FYI: Zack and I pinpointed the issue and it is coming from the API.

Works:
- XPath: /config/shared/address/entry[@name='example 1610562035309526100']
- Element: <ip-netmask>192.168.2.100</ip-netmask><description>Description</description>

Doesn’t work: the Set is doing the bad commit (even without doing a commit)
- XPath: /config/shared/address
- Element: <entry name=\"example 1610562035309526100\"><ip-netmask>192.168.2.100</ip-netmask><description>Description</description></entry>

The way I see it:
1. if passing the entry xml is bad, the API shouldn’t accept it
2. if passing the entry xml is ok, the API shouldn’t do the commit (which includes all objects created by other users)

Zack is going to create a TAC.

**Comment by shinmog** [comment]
Have you approached TAC with this now?  What did TAC say?  I haven't tried this myself yet to verify, but if this is true, this is kind of a big deal...

**Comment by reneherrero** [comment]
The set address action is changing the ownership of all uncommitted address of the same type (device group or shared).

Was able to reproduce it with curl commands and they acknowledged it's a bug.  No ETA on fix.

I propose we leave this open until there's a fix.  You might want to put a "known issues" type note somewhere with the version # that has the fix?  Happening with both 8 & 9

**Comment by shinmog** [comment]
Did they give you a bug ID tracking number?  If so, could you pass that to me?
