### ISSUE TITLE
pango should provide a way to set http headers

### ISSUE THREAD

**Issue by schandrashek** [PaloAltoNetworks/pango#59]
### Is your feature request related to a problem?

pango doesn't provide a way to set http headers. This is a problem for the openconfig plugin where we need to set some http headers to communicate with api server (via a specific port 28250) to get the proper response.

### Describe the solution you'd like

Pango client initialization provides a way to set Protocol, Port, HostName etc. Similarly, we need a way to set the http headers as a key value pair and the post() method in client.go should package the headers into the http request.

### Describe alternatives you've considered

Alternative is to use port 80 to talk with the api server, which may be deprecated in the future in the xmlapi server.

### Additional context

Trying to add support in openconfig plugin to accept client certs. While the TLS cert verification between the external client and openconfig process in the FW is done with the openconfig process, we need to reach out to xmlapi to authorize the request. For this, the openconfig process in panos makes a connection to "http://localhost:28250/api" to authenticate a client(making a gnmi request) using pango api via port 28250. This connection needs specific http headers to be set. Otherwise the server drops the request and the pango api errors out, leading to failed auth errors in openconfig plugin.

Jira bug id: PLUG-7097

**Comment by shinmog** [comment]
From what you describe, it seems like you need a separate `Initialize()` that behaves a certain way.  Is the custom headers only needed at the beginning of client initialization?  Or do the custom headers need to be sent on all subsequent API calls?

**Comment by schandrashek** [comment]
It needs to be sent for all the API calls. Below is a hacked up code of client.go's post()which I had got working:

func (c *Client) post(data url.Values) ([]byte, error) {
    if len(c.rb) == 0 {
        **//SAC
        req, err := NewRequest("POST", c.api_url, strings.NewReader(data.Encode()))
        if err != nil {
            return nil, err
        }
        req.Header.Set("HTTP_X_PAN_AUTHCHECK", "off")
        req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
        r, err := c.doFollowingRedirects(req, shouldRedirectPost)
        //CAS**
        //r, err := c.con.PostForm(c.api_url, data)
        //if err != nil {
        //  return nil, err
        //}

        defer r.Body.Close()
        return ioutil.ReadAll(r.Body)
    } else {
        if c.ri < len(c.rb) {
            c.rp = append(c.rp, data)
        }
        body := c.rb[c.ri%len(c.rb)]
        c.ri++
        return body, nil
    }
}

**Comment by schandrashek** [comment]
As per the discussion today with @kevinsteves, I'm closing this issue. I'll try importing the entire pango lib locally and override the code to set the http headers.

**Comment by shinmog** [comment]
So, seems there is a need for this externally:  PaloAltoNetworks/terraform-provider-panos#273 - so reopening this to add this functionality in.
