### ISSUE TITLE
example_firewall_commit_test.go commit error

### ISSUE THREAD

**Issue by Hax7** [PaloAltoNetworks/pango#63]
I'm using example_firewall_commit_test.go to compile a commit command to use with Terraform but when I run ./commit I get this error every time there is something to be committed "Error in commit: Post "https://172.24.19.4/api": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" but it shows that commits were applied in palo alto and running ./commit again gives no issues.

**Comment by shinmog** [comment]
Making the timeout something the user can configure should allow the commit to succeed.  In your case, you'll just need to specify a timeout greater than 10sec, since 10sec is the default.
