### ISSUE TITLE
Add a function to retrieve a list of the vsys

### ISSUE THREAD

**Issue by Trois-Six** [PaloAltoNetworks/pango#68]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

I would like to be able to list the vsys on a firewall to be able to list all the profiles of all the vsys.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by shinmog** [comment]
This can be done with what's available now:

```go
    path := util.VsysXpathPrefix("vsys1")[:4]
    vsysList, err := fw.EntryListUsing(fw.Get, path)
    if err != nil {
        log.Fatal(err)
    }
    log.Printf("Vsys listing: %v", vsysList)
```
