### ISSUE TITLE
Example for moving rule position in Firewall Policies Rulebase

### ISSUE THREAD

**Issue by rkspx** [PaloAltoNetworks/pango#70]
Hi, thanks for the SDK, it helps so much

Do you have any example code of moving firewall policy position in rulebase using SDK, something like `PoliciesDirect.bulkMovePolicies` in PanDirect or inserting firewall policy at certain position?

The use case is, I have script that automatically creates firewall policy on certain trigger, but I need to insert it after some specific policy.

also, I don't get what `path` parameters in `*Client.Show()` means, the [docs](https://pkg.go.dev/github.com/PaloAltoNetworks/pango#Client.Show) said that it should be either a string or a slice of strings, what string or slice of strings it refers to? is there any documentation for the value I can use for it?

Thank you

**Comment by shinmog** [comment]
This probably belongs in the Discussions instead of as an issue.

To answer the first one, check out the MoveGroup:  https://pkg.go.dev/github.com/PaloAltoNetworks/pango@v0.5.1/poli/security#Firewall.MoveGroup

For the second question, it's the XPATH that you want to `show`.
