### ISSUE TITLE
The default value of OSPF Area Interface Priority

### ISSUE THREAD

**Issue by pbadhan** [PaloAltoNetworks/pango#74]
## Describe the bug

The issue is regarding the following value in PanOS:
`Virtual Router -> OSPF -> Area -> Interface -> Priority`.

## Current behavior

When Priority is configured with a default value which is 1, the value returned by pango is 0. However, Priority can be configured to 0 as its valid range is [0, 255]. This behaviors creates an ambiguous situation for gnmiproxy - it can't tell if the configured value is the default value (1) or 0.

## Expected behavior

The ambiguity described above should be fixed - return 1 as a default value not 0.

## Steps to reproduce

1. Configure an interface is Layer 3 mode and assign it to a zone.
2. Configure virtual router.
3. Add the interface configured in step (1) to the virtual-router.
4. Enable OSPF and configure router ID.
5. Configure an area.
6. Add the interface from step (1) to OSPF.

**Comment by shinmog** [comment]
Need clarification:  is it OSPF area interfaces configured by the GUI that returns 0 if left at the default value of 1, or even if you configure the OSPF interface as 1 with pango, when you `Get()` the config it returns 0 back?

**Comment by pbadhan** [comment]
@shinmog, I tested the former (configuration thru the UI). I don't remember the behavior when changing thru pango.

**Comment by shinmog** [comment]
This should be fixed now.  OSPF area interface priority defaults to 1 when not present in the XML.
