### ISSUE TITLE
New Release when?

### ISSUE THREAD

**Issue by freakytoad1** [PaloAltoNetworks/pango#80]
Would like to use some of the new features since 0.6.0, specifically custom url category support. I can only use versioned releases in my code. When could the next release come out?

**Comment by freakytoad1** [comment]
Wasn't sure the best place to request this.

**Comment by shinmog** [comment]
The Discussions tab would also work :)

But working on the new release now, will be out before the end of the year for sure, just not sure how much more before right now.
