### ISSUE TITLE
Compiling error: extra " at the end of line

### ISSUE THREAD

**Issue by willhu-commit** [PaloAltoNetworks/pango#85]
https://github.com/PaloAltoNetworks/pango/blob/c5ca55a9fa97cb2a6ae74de93fdf9ac59b382398/netw/routing/protocol/ospf/config.go#L150

similiarly:

github.com/PaloAltoNetworks/pango/netw/routing/protocol/ospf/area/entry.go:199:2: struct field tag `xml:"nssa-ext-range""` not compatible with reflect.StructTag.Get: 

github.com/PaloAltoNetworks/pango/netw/routing/protocol/ospf/area/entry.go:203:2: struct field tag `xml:"entry""` not compatible with reflect.StructTag.Get:

**Comment by kevinsteves** [comment]
PR #86 submitted.

**Comment by shinmog** [comment]
This was fixed by #86
