### ISSUE TITLE
support for commit_changes_by?

### ISSUE THREAD

**Issue by gliptak** [PaloAltoNetworks/pango#9]
Could the codebase be updated to support commit_changes_by for both FW and Panorama?

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/panos/_panos_commit.py#L190

https://github.com/PaloAltoNetworks/pango/blob/master/client.go#L416

https://github.com/PaloAltoNetworks/pango/blob/master/pano.go#L85

**Comment by gliptak** [comment]
@shinmog would you accept a patch adding new parameters to ```Commit```/```CommitAll`` signatures supporting this?

**Comment by shinmog** [comment]
@gliptak 

Would definitely be interested in a PR to add support for `commit_changes_by` if you're offering.  Since commits are still not natively handled by Terraform, there would be no rush on this.
